### ISSUE TITLE
Run and track in background?

### ISSUE THREAD

**Issue by orschiro** [frans-fuerst/track#15]
Hi @frans-fuerst,

Thanks for this promising app!

How can I run it in the background and have it tracked all my activity to one file that I can take a look at at the end of the month?

**Comment by frans-fuerst** [comment]
Actually `track` comes with a tracking server which is being started when you start track. You can either start `track` together with your desktop environment or you just start the server by running `track_server.py`.

**Comment by orschiro** [comment]
I see, thank you!

**Comment by frans-fuerst** [comment]
`track_server` can be run as a service manually (e.g. `screen -d -m ./track_server.py`) and it's being started in background together with the `track` main application.
