### ISSUE TITLE
Windows coming -- ever?

### ISSUE THREAD

**Issue by minexew** [frans-fuerst/track#16]
Just wondering if the project is dead or not.

What would it take to get windows support working?

**Comment by frans-fuerst** [comment]
The project is not dead - I just don't have much time right now.
Regarding your request - there _should_ be Windows support but I don't test it regularly. There is even a script which builds a self contained Windows installer.
I'll try to fix windows soon - maybe today or tomorrow!

**Comment by minexew** [comment]
Thanks for the info.
I'm currently evaluating Procrastitracker.
