### ISSUE TITLE
AttributeError: 'module' object has no attribute 'matrix_table_model'

### ISSUE THREAD

**Issue by spock** [frans-fuerst/track#2]
Hi, thanks for the app!

Unfortunately, it doesn't start on my Debian testing:

```
$ ./track
Traceback (most recent call last):
  File "./track", line 8, in <module>
    import track_qt
  File "/home/user/workspace/track/track_qt/__init__.py", line 2, in <module>
    from active_applications import active_applications
  File "/home/user/workspace/track/track_qt/active_applications.py", line 17, in <module>
    class active_applications(track_qt.matrix_table_model):
AttributeError: 'module' object has no attribute 'matrix_table_model'
```

Any ideas on what I could try to make it start?

**Comment by frans-fuerst** [comment]
yes - there was a wrong import order in track_qt. I fixed it a long time ago on my local computer but didn't commit it.
Should work now!

**Comment by spock** [comment]
It does work now, thanks!

**Comment by frans-fuerst** [comment]
note that some features are not implemented yet. E.g. you can't change the 'idle' pattern - currently it's always true if Firefox is on top.

**Comment by spock** [comment]
That's totally fine (and my one is called Iceweasel, so it doesn't trigger idle ;) ). Your 'track' seems to be the only offline Linux-compatible activity tracker... Today I've started a test of RescueTime, Timecamp, and 'track' - want to figure out (after about a week of use) what I really want from such a tracker. As 'track' is in Python, it might end up as the most flexible solution; it is already the only free solution :)

**Comment by frans-fuerst** [comment]
That kind of feedback motivates me to keep up the work - thanks!
